In [2]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress=True)

In [3]:
FoodRating=pd.read_csv("C:/Subhajit/Newfolder/IOT/DS/Machine Learining/PCA/MyFoodRatings.csv")
FoodRating.head()

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0    A        5       5       5         0            0     0      0      0   
1    B        4       4       4         0            0     0      0      0   
2    C        3       3       3         0            0     0      0      0   
3    D        2       2       2         0            0     0      0      0   
4    E        0       0       0         2            2     2      0      0   

   Tempura  
0        0  
1        0  
2        0  
3        0  
4        0

In [4]:
# Drop all non-numeric values
FoodRating.drop('Name',1,inplace=True)

In [5]:
#Covariance matrix
C=np.cov(FoodRating.T)

In [6]:
#eigenvalues decomposition of the matrix
eigenvalues,eigenvectors=np.linalg.eig(C)

In [7]:
#lets sort them
idx=eigenvalues.argsort()[::-1]
eigenvalues=eigenvalues[idx]
eigenvectors=eigenvectors[:,idx]

In [8]:
eigenvalues

array([12.85602099+0.j,  8.54031208+0.j,  1.39224478+0.j,  0.13996673+0.j,
        0.09800524+0.j,  0.01132898+0.j,  0.        +0.j,  0.        -0.j,
       -0.        +0.j])

In [9]:
eigenvectors

array([[ 0.49701863+0.j        ,  0.13426081+0.j        ,
        -0.26050102+0.j        ,  0.00358978+0.j        ,
        -0.01474332+0.j        , -0.013741  +0.j        ,
        -0.26983606-0.27106586j, -0.26983606+0.27106586j,
        -0.02779972+0.j        ],
       [ 0.49701863+0.j        ,  0.13426081+0.j        ,
        -0.26050102+0.j        ,  0.00358978+0.j        ,
        -0.01474332+0.j        , -0.013741  +0.j        ,
        -0.43246086+0.27106586j, -0.43246086-0.27106586j,
         0.09564547+0.j        ],
       [ 0.49701863+0.j        ,  0.13426081+0.j        ,
        -0.26050102+0.j        ,  0.00358978+0.j        ,
        -0.01474332+0.j        , -0.013741  +0.j        ,
         0.70229691+0.j        ,  0.70229691-0.j        ,
        -0.06784575+0.j        ],
       [-0.30044428+0.j        ,  0.44484788+0.j        ,
        -0.38007158+0.j        ,  0.02298208+0.j        ,
         0.63249422+0.j        ,  0.01205857+0.j        ,
        -0.08217086+0.099565

### Using SVD

In [10]:
# use the SVD function from np.linalg library
U,s,VT=np.linalg.svd(FoodRating,full_matrices=True)


In [14]:
U

array([[-0.68041382,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.68395172, -0.2631484 ,  0.        ,
         0.        ,  0.        ],
       [-0.54433105,  0.        ,  0.        , -0.        ,  0.        ,
         0.        , -0.44228188, -0.29276797,  0.64652194, -0.01624405,
         0.05538401, -0.0324881 ],
       [-0.40824829,  0.        ,  0.        , -0.        ,  0.        ,
         0.        , -0.        , -0.65197292, -0.6389559 , -0.        ,
         0.        , -0.        ],
       [-0.27216553, -0.        , -0.        ,  0.        , -0.        ,
        -0.        ,  0.88456377, -0.14638398,  0.32326097,  0.0324881 ,
        -0.11076802,  0.0649762 ],
       [ 0.        , -0.32621702, -0.        ,  0.        , -0.2899287 ,
        -0.        , -0.13325101,  0.        ,  0.        ,  0.21823411,
        -0.7440681 ,  0.43646823],
       [ 0.        , -0.16310851,  0.        , -0.        , -0.14496435,
         0.        ,  

In [12]:
s

array([12.72792206, 10.57703788,  8.84826058,  1.24205263,  1.06125858,
        0.40692755,  0.        ,  0.        ,  0.        ])

In [13]:
np.diag(s[:3])

array([[12.72792206,  0.        ,  0.        ],
       [ 0.        , 10.57703788,  0.        ],
       [ 0.        ,  0.        ,  8.84826058]])

In [26]:
VT.shape

(9, 9)

In [16]:
Vt_DF=pd.DataFrame(VT)
Vt_DF

0         1         2         3         4         5         6  \
0 -0.577350 -0.577350 -0.577350  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000 -0.637875 -0.512261 -0.575068  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000 -0.476163   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.296110   
4 -0.000000 -0.000000 -0.000000  0.653030 -0.755593 -0.051282  0.000000   
5 -0.000000 -0.000000 -0.000000  0.000000  0.000000  0.000000  0.828002   
6  0.000000  0.000000  0.000000 -0.408248 -0.408248  0.816497  0.000000   
7  0.816497 -0.408248 -0.408248  0.000000  0.000000  0.000000  0.000000   
8  0.000000 -0.707107  0.707107  0.000000  0.000000  0.000000  0.000000   

          7         8  
0  0.000000  0.000000  
1  0.000000  0.000000  
2 -0.557638 -0.679933  
3  0.626381 -0.721087  
4  0.000000  0.000000  
5 -0.544690 -0.133137  
6  0.000000  0.000000  
7  0.000000  0.000000  
8  0.000000  0.000000

### relationship between matrices

In [15]:
#Let's denote the eigenvectors matrix as X. This is same as the principal componets
X=eigenvectors
X

array([[ 0.49701863+0.j        ,  0.13426081+0.j        ,
        -0.26050102+0.j        ,  0.00358978+0.j        ,
        -0.01474332+0.j        , -0.013741  +0.j        ,
        -0.26983606-0.27106586j, -0.26983606+0.27106586j,
        -0.02779972+0.j        ],
       [ 0.49701863+0.j        ,  0.13426081+0.j        ,
        -0.26050102+0.j        ,  0.00358978+0.j        ,
        -0.01474332+0.j        , -0.013741  +0.j        ,
        -0.43246086+0.27106586j, -0.43246086-0.27106586j,
         0.09564547+0.j        ],
       [ 0.49701863+0.j        ,  0.13426081+0.j        ,
        -0.26050102+0.j        ,  0.00358978+0.j        ,
        -0.01474332+0.j        , -0.013741  +0.j        ,
         0.70229691+0.j        ,  0.70229691-0.j        ,
        -0.06784575+0.j        ],
       [-0.30044428+0.j        ,  0.44484788+0.j        ,
        -0.38007158+0.j        ,  0.02298208+0.j        ,
         0.63249422+0.j        ,  0.01205857+0.j        ,
        -0.08217086+0.099565

In [21]:
# Projecting the data now by doing  the basis transformation
datn=np.linalg.inv(X) @ FoodRating.T
datn.T

array([[ 7.45527949+0.j,  2.01391214+0.j, -3.90751526-0.j,
         0.05384668+0.j, -0.22114986+0.j, -0.20611503-0.j,
        -0.        +0.j, -0.        +0.j,  0.        +0.j],
       [ 5.96422359+0.j,  1.61112971+0.j, -3.12601221-0.j,
         0.04307735+0.j, -0.17691989+0.j, -0.16489203-0.j,
        -0.        -0.j, -0.        +0.j,  0.        +0.j],
       [ 4.47316769+0.j,  1.20834728+0.j, -2.34450916-0.j,
         0.03230801+0.j, -0.13268992+0.j, -0.12366902-0.j,
        -0.        -0.j, -0.        +0.j,  0.        +0.j],
       [ 2.9821118 +0.j,  0.80556486+0.j, -1.5630061 -0.j,
         0.02153867+0.j, -0.08845995+0.j, -0.08244601-0.j,
        -0.        -0.j, -0.        +0.j,  0.        +0.j],
       [-1.63084465+0.j,  2.39862241+0.j, -1.8463447 -0.j,
         0.01589162+0.j, -0.40761076+0.j, -0.10755672-0.j,
        -0.        -0.j, -0.        +0.j,  0.        +0.j],
       [-0.81542233+0.j,  1.1993112 +0.j, -0.92317235-0.j,
         0.00794581+0.j, -0.20380538+0.j, -0.053778

In [17]:
#Lets comput the U*s matrix
# We have to convert a matrix to a diagonal one
ST=np.diag(s,k=0)

In [19]:
U @ ST

array([[-8.66025404,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , -0.        ],
       [-6.92820323,  0.        ,  0.        , -0.        ,  0.        ,
         0.        , -0.        , -0.        ,  0.        ],
       [-5.19615242,  0.        ,  0.        , -0.        ,  0.        ,
         0.        , -0.        , -0.        , -0.        ],
       [-3.46410162, -0.        , -0.        ,  0.        , -0.        ,
        -0.        ,  0.        , -0.        ,  0.        ],
       [ 0.        , -3.45040973, -0.        ,  0.        , -0.30768932,
        -0.        , -0.        ,  0.        ,  0.        ],
       [ 0.        , -1.72520486,  0.        , -0.        , -0.15384466,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -7.02643309,  0.        ,  0.        ,  0.79324524,
        -0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -6.90081945,  0.        , -0.        , -0

In [17]:
FoodRatings_all_same=pd.read_csv("C:/Subhajit/Newfolder/IOT/DS/Machine Learining/PCA/FoodRatings_all_same_5.csv")
FoodRatings_all_same

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        5       5       5         0            0     0      0      0   
2     C        5       5       5         0            0     0      0      0   
3     D        5       5       5         0            0     0      0      0   
4     E        0       0       0         5            5     5      0      0   
5     F        0       0       0         5            5     5      0      0   
6     G        0       0       0         5            5     5      0      0   
7     H        0       0       0         5            5     5      0      0   
8     I        0       0       0         0            0     0      5      5   
9     J        0       0       0         0            0     0      5      5   
10    K        0       0       0         0            0     0      5      5   
11    L        0       0       0         0            0     0      5      5   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         5  
9         5  
10        5  
11        5

In [19]:
FoodRatings_all_same.drop('Name',1,inplace=True)

In [20]:
U, s, VT = np.linalg.svd(FoodRatings_all_same, full_matrices=True) 

In [21]:
U

array([[ 0.        ,  0.        , -0.5       ,  0.8660254 ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.5       , -0.28867513,  0.81649658,
        -0.        ,  0.        ,  0.        ,  0.        , -0.        ,
        -0.        , -0.        ],
       [ 0.        ,  0.        , -0.5       , -0.28867513, -0.40824829,
        -0.1767767 ,  0.35355339,  0.35355339,  0.35355339, -0.1767767 ,
        -0.1767767 , -0.1767767 ],
       [ 0.        ,  0.        , -0.5       , -0.28867513, -0.40824829,
         0.1767767 , -0.35355339, -0.35355339, -0.35355339,  0.1767767 ,
         0.1767767 ,  0.1767767 ],
       [-0.5       ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.125     ,  0.75      , -0.25      , -0.25      ,  0.125     ,
         0.125     ,  0.125     ],
       [-0.5       ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.125     , -

In [22]:
s

array([17.32050808, 17.32050808, 17.32050808,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [23]:
data=pd.read_csv("C:/Subhajit/Newfolder/IOT/DS/Machine Learining/PCA/FoodRatings_all_same_5_4_3.csv")
data

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        5       5       5         0            0     0      0      0   
2     C        5       5       5         0            0     0      0      0   
3     D        5       5       5         0            0     0      0      0   
4     E        0       0       0         4            4     4      0      0   
5     F        0       0       0         4            4     4      0      0   
6     G        0       0       0         4            4     4      0      0   
7     H        0       0       0         4            4     4      0      0   
8     I        0       0       0         0            0     0      3      3   
9     J        0       0       0         0            0     0      3      3   
10    K        0       0       0         0            0     0      3      3   
11    L        0       0       0         0            0     0      3      3   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         3  
9         3  
10        3  
11        3

In [27]:
data.drop('Name',1,inplace=True)

In [28]:
U,s,VT=np.linalg.svd(data,full_matrices=True)

In [29]:
s

array([17.32050808, 13.85640646, 10.39230485,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])